name: Deploy Google Auth Service

on:
  push:
    branches:
      - main
    paths:
      - services/google-auth-service/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
     contents: 'read'
     id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: "Auth in GCP"
      id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Download JSON file from Google Cloud Storage
      run: |
        gcloud auth list
        gsutil cp gs://${{ secrets.GCS_BUCKET }}/project_variables.json project_variables.json

    - name: Parse JSON and set environment variables using PowerShell
      shell: pwsh
      run: |
        # Read the JSON file
        $jsonString = Get-Content -Raw -Path "project_variables.json"
        $json = $jsonString | ConvertFrom-Json
        
        $projectId = $json.projectId
        $projectNumber = $json.projectNumber
        $region = $json.region
        $artifactRegistryName = $json.artifactRegistryName
        $artifactRegistryId = $json.artifactRegistryId

        Add-Content -Path $env:GITHUB_ENV -Value "PROJECT_ID=$projectId"
        Add-Content -Path $env:GITHUB_ENV -Value "PROJECT_NUMBER=$projectNumber"
        Add-Content -Path $env:GITHUB_ENV -Value "REGION=$region"
        Add-Content -Path $env:GITHUB_ENV -Value "ARTIFACT_REGISTRY_NAME=$artifactRegistryName"
        Add-Content -Path $env:GITHUB_ENV -Value "ARTIFACT_REGISTRY_ID=$artifactRegistryId"

    - name: Docker Auth
      id: docker-auth
      uses: docker/login-action@v3
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.REGION }}-docker.pkg.dev'

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}/google-auth-service:latest .
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}/google-auth-service:latest
      working-directory: services/google-auth-service/src

    - name: Deploy Container
      run: |
        terraform init
        terraform apply --auto-approve
      working-directory: services/google-auth-service/terraform